version: '3'

services:
#   reverse-proxy:
#     container_name: traefik
#     image: traefik # The official Traefik docker image
#     ports:
#       - "80:80"     # The HTTP port
#       - "443:443"
#       - "8080:8080" # The Web UI (enabled by --api)
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
#       - /mnt/jokio_data/server/traefik.toml:/traefik.toml
#       - /mnt/jokio_data/server/acme:/etc/traefik/acme

  contracts-server:
    container_name: contracts-server
    image: registry.jok.io/contracts-server:latest
    restart: always
    ports:
    - "5000:5000"
    environment:
      PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET}
      DB_ENDPOINT:  ${DB_ENDPOINT}
      PRISMA_SECRET:  ${PRISMA_SECRET}


  contracts-web:
    container_name: contracts-web
    image: registry.jok.io/contracts-web:latest
    restart: always
    ports:
    - "80:4200"


  prisma:
    container_name: prisma-service
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: mysql
            port: 3306
            user: root
            password: prisma

  mysql:
    container_name: prisma-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - db-persistence:/var/lib/mysql

  # neo4j:
  #   container_name: neo4j
  #   image: neo4j:3.4.1
  #   restart: always
  #   ports:
  #   - "7474:7474"
  #   - "7687:7687"
  #   volumes:
  #   - /neo4j/data:/data
  #   # - /mnt/jokio_data/neo4j/logs:/logs
  #   - /neo4j/plugins:/plugins
  #   environment:
  #     NEO4J_dbms_memory_heap_maxSize: 300M
  #     NEO4J_dbms_unmanaged__extension__classes: org.neo4j.graphql=/graphql
  #     NEO4J_dbms_security_procedures_unrestricted: graphql.*,apoc.*
  #   labels:
  #     - "traefik.backend=neo4j"
  #     - "traefik.frontend.rule=Host:contracts-db.jok.io"
  #     - "traefik.enable=true"
  #     - "traefik.port=7474"


volumes:
  db-persistence: